window.YES123Seed = {
  tools: [
    {
      id: "lovart",
      title: "Lovart",
      description: "设计 Agent 平台，适合做品牌视觉、海报和创意图形探索。",
      category: "图像",
      tags: ["设计", "海报", "品牌"],
      url: "https://lovart.ai/",
      mediaClass: "media-gradient-1",
      mediaText: "Design Agent",
      logo: "LV",
      sortOrder: 10
    },
    {
      id: "evermemos",
      title: "EverMemOS",
      description: "企业级 AI 长时记忆系统，为智能体提供跨会话和跨平台的长期记忆能力。",
      category: "基础设施",
      tags: ["企业", "记忆", "智能体"],
      url: "https://github.com/Evermem/evermemos",
      mediaClass: "media-gradient-2",
      mediaText: "Long-Term Memory",
      logo: "EM",
      sortOrder: 20
    },
    {
      id: "tripo",
      title: "Tripo",
      description: "面向 AI 3D 生产的工作站型产品，适合模型生成和 3D 创作流程。",
      category: "3D",
      tags: ["3D", "建模", "创作"],
      url: "https://www.tripo3d.ai/",
      mediaClass: "media-gradient-3",
      mediaText: "AI 3D Studio",
      logo: "TP",
      sortOrder: 30
    },
    {
      id: "joypix-ai",
      title: "JoyPix AI",
      description: "一站式 AI 视频与图像生成平台，覆盖图生视频、文生视频和数字人口播。",
      category: "图像",
      tags: ["视频", "图像", "数字人"],
      url: "https://www.joypix.ai/",
      mediaClass: "media-gradient-4",
      mediaText: "Video + Image",
      logo: "JP",
      sortOrder: 40
    },
    {
      id: "ai-song-generator",
      title: "AI Song Generator",
      description: "输入主题或歌词后快速产出歌曲 Demo，适合音频生成和创作灵感。",
      category: "音频",
      tags: ["音乐", "歌曲", "创作"],
      url: "https://aisonggenerator.io/",
      mediaClass: "media-gradient-5",
      mediaText: "Song Generator",
      logo: "SG",
      sortOrder: 50
    },
    {
      id: "pitchlab",
      title: "pitchlab",
      description: "表达能力训练助手，支持自定义人设和实时对话，偏陪练和表达场景。",
      category: "独角兽",
      tags: ["表达", "训练", "对话"],
      url: "https://pitchlab.app/",
      mediaClass: "media-gradient-6",
      mediaText: "Practice Your Pitch",
      logo: "PL",
      sortOrder: 60
    },
    {
      id: "video-watermark-remover",
      title: "Video Watermark Remover",
      description: "自动去除视频中的水印、文字和时间戳，适合基础的视频清理工作。",
      category: "视频",
      tags: ["去水印", "视频处理", "编辑"],
      url: "https://www.media.io/remove-video-watermark.html",
      mediaClass: "media-gradient-7",
      mediaText: "Remove Watermark",
      logo: "VR",
      sortOrder: 70
    },
    {
      id: "ai-manga-translator",
      title: "AI Manga Translator",
      description: "面向漫画图像的自动识别与翻译工具，适合图像 OCR 和跨语种转换。",
      category: "图像",
      tags: ["翻译", "漫画", "OCR"],
      url: "https://mangatranslator.app/",
      mediaClass: "media-gradient-8",
      mediaText: "Manga Translator",
      logo: "MT",
      sortOrder: 80
    },
    {
      id: "koalaqa",
      title: "KoalaQA",
      description: "开源智能售后问答产品，可用于企业客服、运营洞察和知识库问答。",
      category: "基础设施",
      tags: ["客服", "问答", "知识库"],
      url: "https://koala.sh/",
      mediaClass: "media-gradient-9",
      mediaText: "Enterprise QA",
      logo: "KQ",
      sortOrder: 90
    },
    {
      id: "gemini-3-ai",
      title: "Gemini 3 AI",
      description: "通用对话与搜索场景入口，适合整理资料、问答和联网检索。",
      category: "通用Chatbot",
      tags: ["问答", "搜索", "对话"],
      url: "https://gemini.google.com/",
      mediaClass: "media-gradient-10",
      mediaText: "Gemini Chat",
      logo: "GM",
      sortOrder: 100
    },
    {
      id: "aiai",
      title: "AIAI.com",
      description: "图像和视频生成的综合创作平台，适合作为视频类工具入口。",
      category: "视频",
      tags: ["图像", "视频", "生成"],
      url: "https://aiai.com/",
      mediaClass: "media-gradient-11",
      mediaText: "All in One AI",
      logo: "AI",
      sortOrder: 110
    },
    {
      id: "ppt-ai",
      title: "PPT.AI",
      description: "将想法快速转成演示文稿的 AI 办公工具，适合高频演示和汇报需求。",
      category: "办公",
      tags: ["PPT", "演示", "办公"],
      url: "https://ppt.ai/",
      mediaClass: "media-gradient-12",
      mediaText: "AI PPT Maker",
      logo: "PP",
      sortOrder: 120
    }
  ],
  topHot: [
    { label: "AI Agent 正成为企业数字员工入口", sortOrder: 10 },
    { label: "国产视频模型更新节奏明显加快", sortOrder: 20 },
    { label: "企业知识库与客服场景继续升温", sortOrder: 30 },
    { label: "AI 导航与门户内容开始融合", sortOrder: 40 }
  ],
  hotTopics: [
    { title: "AI 创业观察", heat: "120252", sortOrder: 10 },
    { title: "企业部署大模型避坑", heat: "109664", sortOrder: 20 },
    { title: "短视频带货工具榜", heat: "47072", sortOrder: 30 },
    { title: "国产视频模型横评", heat: "44742", sortOrder: 40 },
    { title: "客服机器人方案集", heat: "44433", sortOrder: 50 },
    { title: "品牌 logo 工具推荐", heat: "42934", sortOrder: 60 },
    { title: "AI 写作工具新功能", heat: "41030", sortOrder: 70 },
    { title: "PPT 自动生成案例", heat: "37011", sortOrder: 80 },
    { title: "企业知识库热门模板", heat: "34332", sortOrder: 90 },
    { title: "Agent 产品设计思路", heat: "34197", sortOrder: 100 }
  ],
  events: [
    {
      id: "evt-001",
      title: "2026 北京国际人工智能与机器人创新博览会",
      date: "2026-03-18",
      endDate: "2026-03-20",
      city: "北京",
      address: "朝阳区北三环东路6号·中国国际展览中心朝阳馆",
      lng: 116.4417,
      lat: 39.9656,
      category: "conference",
      tags: ["大模型", "机器人", "AIoT"],
      url: "",
      source: "北京人工智能学会",
      organizer: "北京人工智能学会、北京恒辉国际展览有限公司",
      theme: "京聚全球智，AI创未来",
      free: false
    },
    {
      id: "evt-002",
      title: "2026 中关村论坛年会",
      date: "2026-03-25",
      endDate: "2026-03-29",
      city: "北京",
      address: "海淀区中关村大街·中关村国家自主创新示范区展示中心",
      lng: 116.3107,
      lat: 39.9830,
      category: "conference",
      tags: ["科技创新", "人工智能", "产业融合"],
      url: "",
      source: "官方",
      organizer: "科技部、国家发改委、工信部、北京市政府等",
      theme: "科技创新与产业创新深度融合",
      free: false
    },
    {
      id: "evt-003",
      title: "GDPS 2026 全球开发者先锋大会（含 OpenClaw 黑客松）",
      date: "2026-03-27",
      endDate: "2026-03-29",
      city: "上海",
      address: "徐汇区龙腾大道2555号·西岸国际会展中心",
      lng: 121.4485,
      lat: 31.1688,
      category: "conference",
      tags: ["AI Agent", "OpenClaw", "AI Coding", "具身智能"],
      url: "https://gdps.org.cn/",
      source: "官方",
      organizer: "上海市人工智能行业协会（WAIC组委会指导）",
      theme: "产业出题·科技答题",
      free: false
    },
    {
      id: "evt-004",
      title: "深圳国际人工智能展览会 2026",
      date: "2026-04-09",
      endDate: "2026-04-11",
      city: "深圳",
      address: "福田区福华三路·深圳会展中心",
      lng: 114.0507,
      lat: 22.5330,
      category: "conference",
      tags: ["人工智能", "企业展示", "技术交流"],
      url: "",
      source: "官方",
      organizer: "深圳市相关行业组织",
      theme: "AI 品牌推广与技术交流一站式平台",
      free: false
    },
    {
      id: "evt-005",
      title: "CIO时代华东 AI 峰会",
      date: "2026-04-18",
      endDate: "2026-04-18",
      city: "苏州",
      address: "苏州工业园区·苏州国际博览中心",
      lng: 120.7132,
      lat: 31.3180,
      category: "conference",
      tags: ["企业数字化", "AI 落地", "CIO"],
      url: "",
      source: "官方",
      organizer: "CIO时代、新基建创新研究院、CIO时代华东院",
      theme: "智聚AI·数领未来",
      free: false
    },
    {
      id: "evt-006",
      title: "CIAI 2026 第十一届中国国际人工智能大会暨展览会",
      date: "2026-05-06",
      endDate: "2026-05-09",
      city: "上海",
      address: "青浦区崧泽大道333号·国家会展中心（上海）",
      lng: 121.2940,
      lat: 31.1952,
      category: "conference",
      tags: ["算力", "算法", "大模型"],
      url: "",
      source: "官方",
      organizer: "中国人工智能产业联盟",
      theme: "人工智能算力与算法",
      free: false
    },
    {
      id: "evt-007",
      title: "全国人工智能产业发展大会暨杭州国际人工智能展",
      date: "2026-05-13",
      endDate: "2026-05-15",
      city: "杭州",
      address: "萧山区奔竞大道353号·杭州国际博览中心",
      lng: 120.2695,
      lat: 30.2135,
      category: "conference",
      tags: ["AI 核心技术", "智能终端", "应用赋能"],
      url: "http://www.chinacimae.com/",
      source: "官方",
      organizer: "全国人工智能产业发展大会组委会",
      theme: "AI 应用创新与低空经济发展",
      free: false
    },
    {
      id: "evt-008",
      title: "GAIE 2026 全球人工智能终端展暨第七届深圳国际人工智能展",
      date: "2026-05-14",
      endDate: "2026-05-16",
      city: "深圳",
      address: "福田区福华三路·深圳会展中心1号馆",
      lng: 114.0510,
      lat: 22.5335,
      category: "conference",
      tags: ["AI 终端", "AI 手机", "AI 计算机"],
      url: "https://www.gaie.com.cn/",
      source: "官方",
      organizer: "深圳市人工智能行业协会、深圳会展中心",
      theme: "AI 终端产业九大品类展示",
      free: false
    },
    {
      id: "evt-009",
      title: "CCAI 2026 第六届计算机通信与人工智能国际会议",
      date: "2026-05-22",
      endDate: "2026-05-24",
      city: "南京",
      address: "江宁区宁六路219号·南京信息工程大学",
      lng: 118.7176,
      lat: 32.2064,
      category: "conference",
      tags: ["学术", "计算机通信", "论文"],
      url: "https://www.ccai.net/",
      source: "官方",
      organizer: "南京信息工程大学（NUIST）",
      theme: "计算机通信与人工智能学术交流（IEEE收录）",
      free: false
    },
    {
      id: "evt-010",
      title: "MWC 上海 2026 世界移动通信大会",
      date: "2026-06-24",
      endDate: "2026-06-26",
      city: "上海",
      address: "浦东新区龙阳路2345号·上海新国际博览中心",
      lng: 121.5580,
      lat: 31.2044,
      category: "conference",
      tags: ["移动AI", "具身智能", "6G"],
      url: "https://www.mwcshanghai.cn/",
      source: "官方",
      organizer: "GSMA",
      theme: "移动AI、具身智能/人形机器人、6G",
      free: false
    },
    {
      id: "evt-011",
      title: "WAIC 2026 世界人工智能大会",
      date: "2026-07-03",
      endDate: "2026-07-05",
      city: "上海",
      address: "浦东新区博成路850号·上海世博中心及世博展览馆",
      lng: 121.4911,
      lat: 31.1879,
      category: "conference",
      tags: ["大模型", "AI Agent", "具身智能", "产业生态"],
      url: "https://worldaic.com.cn/",
      source: "官方",
      organizer: "国家多部委联合主办",
      theme: "中国规格最高的AI产业大会",
      free: false
    },
    {
      id: "evt-012",
      title: "OpenClaw「虾搞」数据库专场·杭州",
      date: "2026-03-14",
      endDate: "2026-03-14",
      city: "杭州",
      address: "余杭区文一西路969号·阿里西溪园区",
      lng: 120.0255,
      lat: 30.2882,
      category: "meetup",
      tags: ["OpenClaw", "AI Agent", "数据库"],
      url: "",
      source: "社区",
      organizer: "阿里云",
      theme: "AI Agent 与数据库融合",
      free: true
    },
    {
      id: "evt-013",
      title: "OPC 硬核 Meetup 杭州站",
      date: "2026-03-14",
      endDate: "2026-03-14",
      city: "杭州",
      address: "余杭区仓前街道·云谷中心",
      lng: 119.9907,
      lat: 30.2866,
      category: "meetup",
      tags: ["OpenClaw", "Workshop", "实操"],
      url: "",
      source: "社区",
      organizer: "OPC 社区",
      theme: "用 OpenClaw 做出来，才算数",
      free: true
    },
    {
      id: "evt-014",
      title: "OpenClaw「碰撞场」北京首场",
      date: "2026-03-07",
      endDate: "2026-03-08",
      city: "北京",
      address: "海淀区成府路28号·五道口原点学堂",
      lng: 116.3378,
      lat: 39.9925,
      category: "meetup",
      tags: ["OpenClaw", "AI Agent", "实战 Demo"],
      url: "",
      source: "社区",
      organizer: "中关村原生引擎、TTC、九合创投",
      theme: "AI Agent 落地实战·8组 OpenClaw 实战 Demo",
      free: true
    },
    {
      id: "evt-015",
      title: "OpenClaw 生态主题分享会·深圳福田",
      date: "2026-03-10",
      endDate: "2026-03-10",
      city: "深圳",
      address: "福田区梅林街道·新一代产业园",
      lng: 114.0552,
      lat: 22.5612,
      category: "salon",
      tags: ["OpenClaw", "商业生态", "创业"],
      url: "",
      source: "社区",
      organizer: "中山大学管理学院、深圳报业集团、福田产投",
      theme: "OpenClaw 商业新生态·破界共生",
      free: true
    },
    {
      id: "evt-016",
      title: "九合 OpenClaw Meetup 深圳站",
      date: "2026-03-08",
      endDate: "2026-03-09",
      city: "深圳",
      address: "南山区粤海街道·深圳湾科技生态园",
      lng: 113.9470,
      lat: 22.5230,
      category: "meetup",
      tags: ["OpenClaw", "AI 硬件", "创业"],
      url: "",
      source: "社区",
      organizer: "九合创投",
      theme: "Founder都在用 OpenClaw 做什么",
      free: true
    },
    {
      id: "evt-017",
      title: "养虾社 Weekly Meetup 北京站",
      date: "2026-03-15",
      endDate: "2026-03-15",
      city: "北京",
      address: "海淀区中关村·具体地址见 Luma 报名页",
      lng: 116.3107,
      lat: 39.9830,
      category: "meetup",
      tags: ["OpenClaw", "圆桌座谈", "快闪演讲"],
      url: "",
      source: "社区",
      organizer: "养虾社、Manus Academy",
      theme: "OpenClaw 技术分享与圆桌座谈",
      free: true
    }
  ],
  headlines: [
    { text: "AI 企业工具导航正在从“工具合集”变成“直接可用入口”", sortOrder: 10 },
    { text: "国产大模型生态持续扩张，视频、办公、客服仍是更新最快的三类", sortOrder: 20 }
  ],
  newsArticles: [
    {
      title: "AI 导航首页为什么要加资讯区",
      summary: "参考门户站思路，资讯区的作用不是做长内容，而是持续给首页提供热点和停留理由。",
      meta: "好点 AI 编辑部 · 7 小时前更新",
      imageVariant: "default",
      sortOrder: 10
    },
    {
      title: "企业用户更关心“能不能直接用”",
      summary: "像 logo 生成、智能客服、PPT 自动化这类工具，应该在导航页就能被直接找到并点击使用。",
      meta: "行业观察 · 18 天前更新",
      imageVariant: "alt",
      sortOrder: 20
    },
    {
      title: "参考 hao123，右侧更适合热点和推荐",
      summary: "常见组合是热点、推荐资讯、视频内容和常用入口混排，而不是纯文章列表。",
      meta: "产品规划 · 27 天前更新",
      imageVariant: "third",
      sortOrder: 30
    }
  ],
  videos: [
    {
      title: "AI 办公 3 分钟提效技巧合集",
      summary: "模拟抖音未登录推荐流里的视频卡片，正式版可以换成真实封面和标题。",
      url: "https://www.douyin.com/",
      imageVariant: "default",
      sortOrder: 10
    },
    {
      title: "Logo 设计工具实测对比",
      summary: "适合插在热点资讯中间，形成图文资讯和短视频混排的门户感。",
      url: "https://www.douyin.com/",
      imageVariant: "alt",
      sortOrder: 20
    },
    {
      title: "短视频账号起号素材灵感",
      summary: "当前不直接嵌真实抖音首页，而是用推荐卡片承接，落地更稳。",
      url: "https://www.douyin.com/",
      imageVariant: "third",
      sortOrder: 30
    }
  ]
};
