window.HaodianSeed = {
  tools: [
    {
      id: "lovart",
      title: "Lovart",
      description: "设计 Agent 平台，适合做品牌视觉、海报和创意图形探索。",
      category: "图像",
      group: "图像",
      tags: ["设计", "海报", "品牌"],
      url: "https://lovart.ai/",
      screenshot: "screenshots/lovart.png",
      mediaClass: "media-gradient-1",
      mediaText: "Design Agent",
      logo: "LV",
      sortOrder: 10
    },
    {
      id: "evermemos",
      title: "EverMemOS",
      description: "企业级 AI 长时记忆系统，为智能体提供跨会话和跨平台的长期记忆能力。",
      category: "基础设施",
      group: "效率",
      tags: ["企业", "记忆", "智能体"],
      url: "https://github.com/Evermem/evermemos",
      mediaClass: "media-gradient-2",
      mediaText: "Long-Term Memory",
      logo: "EM",
      sortOrder: 20
    },
    {
      id: "tripo",
      title: "Tripo",
      description: "面向 AI 3D 生产的工作站型产品，适合模型生成和 3D 创作流程。",
      category: "3D",
      group: "图像",
      tags: ["3D", "建模", "创作"],
      url: "https://www.tripo3d.ai/",
      screenshot: "screenshots/tripo.png",
      mediaClass: "media-gradient-3",
      mediaText: "AI 3D Studio",
      logo: "TP",
      sortOrder: 30
    },
    {
      id: "joypix-ai",
      title: "JoyPix AI",
      description: "一站式 AI 视频与图像生成平台，覆盖图生视频、文生视频和数字人口播。",
      category: "图像",
      group: "图像",
      tags: ["视频", "图像", "数字人"],
      url: "https://www.joypix.ai/",
      screenshot: "screenshots/joypix.png",
      mediaClass: "media-gradient-4",
      mediaText: "Video + Image",
      logo: "JP",
      sortOrder: 40
    },
    {
      id: "ai-song-generator",
      title: "AI Song Generator",
      description: "输入主题或歌词后快速产出歌曲 Demo，适合音频生成和创作灵感。",
      category: "音频",
      group: "音频",
      tags: ["音乐", "歌曲", "创作"],
      url: "https://aisonggenerator.io/",
      screenshot: "screenshots/aisonggenerator.png",
      mediaClass: "media-gradient-5",
      mediaText: "Song Generator",
      logo: "SG",
      sortOrder: 50
    },
    {
      id: "pitchlab",
      title: "pitchlab",
      description: "表达能力训练助手，支持自定义人设和实时对话，偏陪练和表达场景。",
      category: "独角兽",
      group: "效率",
      tags: ["表达", "训练", "对话"],
      url: "https://pitchlab.app/",
      screenshot: "screenshots/pitchlab.png",
      mediaClass: "media-gradient-6",
      mediaText: "Practice Your Pitch",
      logo: "PL",
      sortOrder: 60
    },
    {
      id: "video-watermark-remover",
      title: "Video Watermark Remover",
      description: "自动去除视频中的水印、文字和时间戳，适合基础的视频清理工作。",
      category: "视频",
      group: "视频",
      tags: ["去水印", "视频处理", "编辑"],
      url: "https://www.media.io/remove-video-watermark.html",
      screenshot: "screenshots/media-io.png",
      mediaClass: "media-gradient-7",
      mediaText: "Remove Watermark",
      logo: "VR",
      sortOrder: 70
    },
    {
      id: "ai-manga-translator",
      title: "AI Manga Translator",
      description: "面向漫画图像的自动识别与翻译工具，适合图像 OCR 和跨语种转换。",
      category: "图像",
      group: "文本",
      tags: ["翻译", "漫画", "OCR"],
      url: "https://mangatranslator.app/",
      mediaClass: "media-gradient-8",
      mediaText: "Manga Translator",
      logo: "MT",
      sortOrder: 80
    },
    {
      id: "koalaqa",
      title: "KoalaQA",
      description: "开源智能售后问答产品，可用于企业客服、运营洞察和知识库问答。",
      category: "基础设施",
      group: "效率",
      tags: ["客服", "问答", "知识库"],
      url: "https://koala.sh/",
      screenshot: "screenshots/koala.png",
      mediaClass: "media-gradient-9",
      mediaText: "Enterprise QA",
      logo: "KQ",
      sortOrder: 90
    },
    {
      id: "gemini-3-ai",
      title: "Gemini 3 AI",
      description: "通用对话与搜索场景入口，适合整理资料、问答和联网检索。",
      category: "通用Chatbot",
      group: "文本",
      tags: ["问答", "搜索", "对话"],
      url: "https://gemini.google.com/",
      screenshot: "screenshots/gemini.png",
      mediaClass: "media-gradient-10",
      mediaText: "Gemini Chat",
      logo: "GM",
      sortOrder: 100
    },
    {
      id: "aiai",
      title: "AIAI.com",
      description: "图像和视频生成的综合创作平台，适合作为视频类工具入口。",
      category: "视频",
      group: "视频",
      tags: ["图像", "视频", "生成"],
      url: "https://aiai.com/",
      screenshot: "screenshots/aiai.png",
      mediaClass: "media-gradient-11",
      mediaText: "All in One AI",
      logo: "AI",
      sortOrder: 110
    },
    {
      id: "ppt-ai",
      title: "PPT.AI",
      description: "将想法快速转成演示文稿的 AI 办公工具，适合高频演示和汇报需求。",
      category: "办公",
      group: "效率",
      tags: ["PPT", "演示", "办公"],
      url: "https://ppt.ai/",
      screenshot: "screenshots/ppt-ai.png",
      mediaClass: "media-gradient-12",
      mediaText: "AI PPT Maker",
      logo: "PP",
      sortOrder: 120
    },
    {
      id: "logo-generator",
      title: "Logo 生成",
      description: "快速生成 Logo 徽标，让品牌形象焕然一新，支持多种风格和格式导出。",
      category: "图像",
      group: "图像",
      tags: ["Logo", "品牌", "设计"],
      url: "https://www.logoai.com/",
      screenshot: "screenshots/logoai.png",
      mediaClass: "media-gradient-1",
      mediaText: "Logo Generator",
      logo: "LG",
      sortOrder: 130
    },
    {
      id: "speech-to-text",
      title: "转录 | 语音转文字",
      description: "会议、采访或视频内容的快速转录，支持多语种识别和时间戳标注。",
      category: "音频",
      group: "音频",
      tags: ["转录", "语音", "会议"],
      url: "https://otter.ai/",
      screenshot: "screenshots/otter.png",
      mediaClass: "media-gradient-9",
      mediaText: "Speech to Text",
      logo: "ST",
      sortOrder: 140
    },
    {
      id: "writing-assistant",
      title: "写作助手",
      description: "帮助妙笔生花的 AI 工具，支持文章润色、续写、改写和多语种翻译。",
      category: "写作",
      group: "文本",
      tags: ["写作", "润色", "创作"],
      url: "https://www.jasper.ai/",
      screenshot: "screenshots/jasper.png",
      mediaClass: "media-gradient-6",
      mediaText: "Writing Assistant",
      logo: "WA",
      sortOrder: 150
    },
    {
      id: "text-summary",
      title: "文本摘要总结",
      description: "将长文内容进行总结提炼，节省你的宝贵时间，支持多种输出格式。",
      category: "写作",
      group: "文本",
      tags: ["摘要", "总结", "效率"],
      url: "https://www.summarize.tech/",
      screenshot: "screenshots/summarize.png",
      mediaClass: "media-gradient-2",
      mediaText: "Text Summary",
      logo: "TS",
      sortOrder: 160
    },
    {
      id: "text-to-video",
      title: "文字生成视频",
      description: "输入一段文本，生成相应的视频内容，适合短视频和营销素材制作。",
      category: "视频",
      group: "视频",
      tags: ["视频生成", "文生视频", "营销"],
      url: "https://www.synthesia.io/",
      screenshot: "screenshots/synthesia.png",
      mediaClass: "media-gradient-4",
      mediaText: "Text to Video",
      logo: "TV",
      sortOrder: 170
    },
    {
      id: "video-editor",
      title: "视频剪辑提取",
      description: "利用 AI 技术对视频进行快速编辑，支持自动剪辑、字幕生成和片段提取。",
      category: "视频",
      group: "视频",
      tags: ["剪辑", "编辑", "字幕"],
      url: "https://www.capcut.com/",
      screenshot: "screenshots/capcut.png",
      mediaClass: "media-gradient-8",
      mediaText: "Video Editor",
      logo: "VE",
      sortOrder: 180
    },
    {
      id: "ppt-generator",
      title: "PPT 生成",
      description: "输入文字，立即生成精美 PPT，支持多种模板和自动排版布局。",
      category: "办公",
      group: "效率",
      tags: ["PPT", "演示", "模板"],
      url: "https://gamma.app/",
      screenshot: "screenshots/gamma.png",
      mediaClass: "media-gradient-10",
      mediaText: "PPT Generator",
      logo: "PG",
      sortOrder: 190
    },
    {
      id: "mindmap-generator",
      title: "思维导图生成",
      description: "AI 根据用户输入自动创建思维导图，清晰地呈现和整理复杂信息结构。",
      category: "办公",
      group: "效率",
      tags: ["思维导图", "整理", "知识"],
      url: "https://xmind.ai/",
      screenshot: "screenshots/xmind.png",
      mediaClass: "media-gradient-3",
      mediaText: "Mind Map",
      logo: "MM",
      sortOrder: 200
    },
    {
      id: "text-to-speech",
      title: "文字转语音",
      description: "将书面文字转换为可听见的语音，支持多语种和自定义音色。",
      category: "音频",
      group: "音频",
      tags: ["语音", "朗读", "TTS"],
      url: "https://elevenlabs.io/",
      screenshot: "screenshots/elevenlabs.png",
      mediaClass: "media-gradient-5",
      mediaText: "Text to Speech",
      logo: "TS",
      sortOrder: 210
    },
    {
      id: "website-builder",
      title: "网站生成器",
      description: "AI 自动化创建和设计网站的工具，无需编程即可快速上线。",
      category: "办公",
      group: "效率",
      tags: ["网站", "建站", "无代码"],
      url: "https://www.framer.com/",
      screenshot: "screenshots/framer.png",
      mediaClass: "media-gradient-11",
      mediaText: "Website Builder",
      logo: "WB",
      sortOrder: 220
    },
    {
      id: "image-colorize",
      title: "图像上色",
      description: "利用算法自动为黑白图像添加色彩的技术，适合老照片修复。",
      category: "图像",
      group: "图像",
      tags: ["上色", "修复", "照片"],
      url: "https://palette.fm/",
      screenshot: "screenshots/palette.png",
      mediaClass: "media-gradient-7",
      mediaText: "Image Colorize",
      logo: "IC",
      sortOrder: 230
    },
    {
      id: "image-upscale",
      title: "图像放大 | 增强分辨率",
      description: "通过智能算法重建图像细节，使低分辨率的图片变得更加清晰。",
      category: "图像",
      group: "图像",
      tags: ["放大", "增强", "超分"],
      url: "https://www.topazlabs.com/",
      screenshot: "screenshots/topaz.png",
      mediaClass: "media-gradient-9",
      mediaText: "Image Upscale",
      logo: "IU",
      sortOrder: 240
    },
    {
      id: "bg-remover",
      title: "图像消除背景",
      description: "抠图，轻松从图像中删除背景，支持批量处理和透明背景导出。",
      category: "图像",
      group: "图像",
      tags: ["抠图", "背景", "编辑"],
      url: "https://www.remove.bg/",
      screenshot: "screenshots/removebg.png",
      mediaClass: "media-gradient-12",
      mediaText: "Remove Background",
      logo: "RB",
      sortOrder: 250
    },
    {
      id: "text-to-image",
      title: "文字生成图像",
      description: "只需输入文字，即可产生令人惊叹的图像，支持多种艺术风格。",
      category: "图像",
      group: "图像",
      tags: ["图像生成", "文生图", "艺术"],
      url: "https://www.midjourney.com/",
      screenshot: "screenshots/midjourney.png",
      mediaClass: "media-gradient-2",
      mediaText: "Text to Image",
      logo: "TI",
      sortOrder: 260
    },
    {
      id: "coding-assistant",
      title: "编程助手",
      description: "让编程工作变得更简单、高效，支持代码补全、调试和重构。",
      category: "编程",
      group: "效率",
      tags: ["编程", "代码", "开发"],
      url: "https://github.com/features/copilot",
      screenshot: "screenshots/copilot.png",
      mediaClass: "media-gradient-6",
      mediaText: "Coding Assistant",
      logo: "CA",
      sortOrder: 270
    },
    {
      id: "social-media-ai",
      title: "社交媒体",
      description: "使用 AI 提升社交媒体发布效率，支持文案生成、排期和数据分析。",
      category: "营销",
      group: "效率",
      tags: ["社交", "营销", "运营"],
      url: "https://buffer.com/",
      screenshot: "screenshots/buffer.png",
      mediaClass: "media-gradient-8",
      mediaText: "Social Media AI",
      logo: "SM",
      sortOrder: 280
    }
  ],
  topHot: [
    { label: "AI Agent 正成为企业数字员工入口", sortOrder: 10 },
    { label: "国产视频模型更新节奏明显加快", sortOrder: 20 },
    { label: "企业知识库与客服场景继续升温", sortOrder: 30 },
    { label: "AI 导航与门户内容开始融合", sortOrder: 40 }
  ],
  hotTopics: [
    { title: "AI 创业观察", heat: "120252", sortOrder: 10 },
    { title: "企业部署大模型避坑", heat: "109664", sortOrder: 20 },
    { title: "短视频带货工具榜", heat: "47072", sortOrder: 30 },
    { title: "国产视频模型横评", heat: "44742", sortOrder: 40 },
    { title: "客服机器人方案集", heat: "44433", sortOrder: 50 },
    { title: "品牌 logo 工具推荐", heat: "42934", sortOrder: 60 },
    { title: "AI 写作工具新功能", heat: "41030", sortOrder: 70 },
    { title: "PPT 自动生成案例", heat: "37011", sortOrder: 80 },
    { title: "企业知识库热门模板", heat: "34332", sortOrder: 90 },
    { title: "Agent 产品设计思路", heat: "34197", sortOrder: 100 }
  ],
  events: [
    {
      id: "evt-001",
      title: "2026 北京国际人工智能与机器人创新博览会",
      date: "2026-03-18",
      endDate: "2026-03-20",
      city: "北京",
      address: "朝阳区北三环东路6号·中国国际展览中心朝阳馆",
      lng: 116.4417,
      lat: 39.9656,
      category: "conference",
      tags: ["大模型", "机器人", "AIoT"],
      url: "",
      source: "北京人工智能学会",
      organizer: "北京人工智能学会、北京恒辉国际展览有限公司",
      theme: "京聚全球智，AI创未来",
      free: false
    },
    {
      id: "evt-002",
      title: "2026 中关村论坛年会",
      date: "2026-03-25",
      endDate: "2026-03-29",
      city: "北京",
      address: "海淀区中关村大街·中关村国家自主创新示范区展示中心",
      lng: 116.3107,
      lat: 39.9830,
      category: "conference",
      tags: ["科技创新", "人工智能", "产业融合"],
      url: "",
      source: "官方",
      organizer: "科技部、国家发改委、工信部、北京市政府等",
      theme: "科技创新与产业创新深度融合",
      free: false
    },
    {
      id: "evt-003",
      title: "GDPS 2026 全球开发者先锋大会（含 OpenClaw 黑客松）",
      date: "2026-03-27",
      endDate: "2026-03-29",
      city: "上海",
      address: "徐汇区龙腾大道2555号·西岸国际会展中心",
      lng: 121.4485,
      lat: 31.1688,
      category: "conference",
      tags: ["AI Agent", "OpenClaw", "AI Coding", "具身智能"],
      url: "https://gdps.org.cn/",
      source: "官方",
      organizer: "上海市人工智能行业协会（WAIC组委会指导）",
      theme: "产业出题·科技答题",
      free: false
    },
    {
      id: "evt-004",
      title: "深圳国际人工智能展览会 2026",
      date: "2026-04-09",
      endDate: "2026-04-11",
      city: "深圳",
      address: "福田区福华三路·深圳会展中心",
      lng: 114.0507,
      lat: 22.5330,
      category: "conference",
      tags: ["人工智能", "企业展示", "技术交流"],
      url: "",
      source: "官方",
      organizer: "深圳市相关行业组织",
      theme: "AI 品牌推广与技术交流一站式平台",
      free: false
    },
    {
      id: "evt-005",
      title: "CIO时代华东 AI 峰会",
      date: "2026-04-18",
      endDate: "2026-04-18",
      city: "苏州",
      address: "苏州工业园区·苏州国际博览中心",
      lng: 120.7132,
      lat: 31.3180,
      category: "conference",
      tags: ["企业数字化", "AI 落地", "CIO"],
      url: "",
      source: "官方",
      organizer: "CIO时代、新基建创新研究院、CIO时代华东院",
      theme: "智聚AI·数领未来",
      free: false
    },
    {
      id: "evt-006",
      title: "CIAI 2026 第十一届中国国际人工智能大会暨展览会",
      date: "2026-05-06",
      endDate: "2026-05-09",
      city: "上海",
      address: "青浦区崧泽大道333号·国家会展中心（上海）",
      lng: 121.2940,
      lat: 31.1952,
      category: "conference",
      tags: ["算力", "算法", "大模型"],
      url: "",
      source: "官方",
      organizer: "中国人工智能产业联盟",
      theme: "人工智能算力与算法",
      free: false
    },
    {
      id: "evt-007",
      title: "全国人工智能产业发展大会暨杭州国际人工智能展",
      date: "2026-05-13",
      endDate: "2026-05-15",
      city: "杭州",
      address: "萧山区奔竞大道353号·杭州国际博览中心",
      lng: 120.2695,
      lat: 30.2135,
      category: "conference",
      tags: ["AI 核心技术", "智能终端", "应用赋能"],
      url: "http://www.chinacimae.com/",
      source: "官方",
      organizer: "全国人工智能产业发展大会组委会",
      theme: "AI 应用创新与低空经济发展",
      free: false
    },
    {
      id: "evt-008",
      title: "GAIE 2026 全球人工智能终端展暨第七届深圳国际人工智能展",
      date: "2026-05-14",
      endDate: "2026-05-16",
      city: "深圳",
      address: "福田区福华三路·深圳会展中心1号馆",
      lng: 114.0510,
      lat: 22.5335,
      category: "conference",
      tags: ["AI 终端", "AI 手机", "AI 计算机"],
      url: "https://www.gaie.com.cn/",
      source: "官方",
      organizer: "深圳市人工智能行业协会、深圳会展中心",
      theme: "AI 终端产业九大品类展示",
      free: false
    },
    {
      id: "evt-009",
      title: "CCAI 2026 第六届计算机通信与人工智能国际会议",
      date: "2026-05-22",
      endDate: "2026-05-24",
      city: "南京",
      address: "江宁区宁六路219号·南京信息工程大学",
      lng: 118.7176,
      lat: 32.2064,
      category: "conference",
      tags: ["学术", "计算机通信", "论文"],
      url: "https://www.ccai.net/",
      source: "官方",
      organizer: "南京信息工程大学（NUIST）",
      theme: "计算机通信与人工智能学术交流（IEEE收录）",
      free: false
    },
    {
      id: "evt-010",
      title: "MWC 上海 2026 世界移动通信大会",
      date: "2026-06-24",
      endDate: "2026-06-26",
      city: "上海",
      address: "浦东新区龙阳路2345号·上海新国际博览中心",
      lng: 121.5580,
      lat: 31.2044,
      category: "conference",
      tags: ["移动AI", "具身智能", "6G"],
      url: "https://www.mwcshanghai.cn/",
      source: "官方",
      organizer: "GSMA",
      theme: "移动AI、具身智能/人形机器人、6G",
      free: false
    },
    {
      id: "evt-011",
      title: "WAIC 2026 世界人工智能大会",
      date: "2026-07-03",
      endDate: "2026-07-05",
      city: "上海",
      address: "浦东新区博成路850号·上海世博中心及世博展览馆",
      lng: 121.4911,
      lat: 31.1879,
      category: "conference",
      tags: ["大模型", "AI Agent", "具身智能", "产业生态"],
      url: "https://worldaic.com.cn/",
      source: "官方",
      organizer: "国家多部委联合主办",
      theme: "中国规格最高的AI产业大会",
      free: false
    },
    {
      id: "evt-012",
      title: "OpenClaw「虾搞」数据库专场·杭州",
      date: "2026-03-14",
      endDate: "2026-03-14",
      city: "杭州",
      address: "余杭区文一西路969号·阿里西溪园区",
      lng: 120.0255,
      lat: 30.2882,
      category: "meetup",
      tags: ["OpenClaw", "AI Agent", "数据库"],
      url: "",
      source: "社区",
      organizer: "阿里云",
      theme: "AI Agent 与数据库融合",
      free: true
    },
    {
      id: "evt-013",
      title: "OPC 硬核 Meetup 杭州站",
      date: "2026-03-14",
      endDate: "2026-03-14",
      city: "杭州",
      address: "余杭区仓前街道·云谷中心",
      lng: 119.9907,
      lat: 30.2866,
      category: "meetup",
      tags: ["OpenClaw", "Workshop", "实操"],
      url: "",
      source: "社区",
      organizer: "OPC 社区",
      theme: "用 OpenClaw 做出来，才算数",
      free: true
    },
    {
      id: "evt-017",
      title: "养虾社 Weekly Meetup 北京站",
      date: "2026-03-15",
      endDate: "2026-03-15",
      city: "北京",
      address: "海淀区中关村·具体地址见 Luma 报名页",
      lng: 116.3107,
      lat: 39.9830,
      category: "meetup",
      tags: ["OpenClaw", "圆桌座谈", "快闪演讲"],
      url: "",
      source: "社区",
      organizer: "养虾社、Manus Academy",
      theme: "OpenClaw 技术分享与圆桌座谈",
      free: true
    }
  ],
  headlines: [
    { text: "AI 企业工具导航正在从“工具合集”变成“直接可用入口”", sortOrder: 10 },
    { text: "国产大模型生态持续扩张，视频、办公、客服仍是更新最快的三类", sortOrder: 20 }
  ],
  newsArticles: [
    {
      title: "AI 导航首页为什么要加资讯区",
      summary: "参考门户站思路，资讯区的作用不是做长内容，而是持续给首页提供热点和停留理由。",
      meta: "好点 AI 编辑部 · 7 小时前更新",
      imageVariant: "default",
      sortOrder: 10
    },
    {
      title: "企业用户更关心“能不能直接用”",
      summary: "像 logo 生成、智能客服、PPT 自动化这类工具，应该在导航页就能被直接找到并点击使用。",
      meta: "行业观察 · 18 天前更新",
      imageVariant: "alt",
      sortOrder: 20
    },
    {
      title: "参考 hao123，右侧更适合热点和推荐",
      summary: "常见组合是热点、推荐资讯、视频内容和常用入口混排，而不是纯文章列表。",
      meta: "产品规划 · 27 天前更新",
      imageVariant: "third",
      sortOrder: 30
    }
  ],
  videos: [
    {
      title: "AI 办公 3 分钟提效技巧合集",
      summary: "模拟抖音未登录推荐流里的视频卡片，正式版可以换成真实封面和标题。",
      url: "https://www.douyin.com/",
      imageVariant: "default",
      sortOrder: 10
    },
    {
      title: "Logo 设计工具实测对比",
      summary: "适合插在热点资讯中间，形成图文资讯和短视频混排的门户感。",
      url: "https://www.douyin.com/",
      imageVariant: "alt",
      sortOrder: 20
    },
    {
      title: "短视频账号起号素材灵感",
      summary: "当前不直接嵌真实抖音首页，而是用推荐卡片承接，落地更稳。",
      url: "https://www.douyin.com/",
      imageVariant: "third",
      sortOrder: 30
    }
  ],
  agents: [
    {
      id: "agent-coze",
      title: "Coze (扣子)",
      description: "字节跳动推出的 AI Bot 开发平台，支持插件、工作流和知识库，零代码搭建智能体。",
      category: "开发平台",
      tags: ["Bot", "工作流", "插件"],
      url: "https://www.coze.cn/",
      screenshot: "screenshots/coze.png",
      mediaClass: "media-gradient-1",
      mediaText: "AI Bot Platform",
      logo: "CZ"
    },
    {
      id: "agent-dify",
      title: "Dify",
      description: "开源 LLM 应用开发平台，提供 RAG、Agent、工作流编排等能力，适合企业私有化部署。",
      category: "开发平台",
      tags: ["开源", "RAG", "工作流"],
      url: "https://dify.ai/",
      screenshot: "screenshots/dify.png",
      mediaClass: "media-gradient-5",
      mediaText: "LLM App Engine",
      logo: "DF"
    },
    {
      id: "agent-manus",
      title: "Manus",
      description: "通用 AI Agent，能自主完成复杂任务，包括调研、数据分析、文档撰写等。",
      category: "通用Agent",
      tags: ["自主", "调研", "分析"],
      url: "https://manus.im/",
      screenshot: "screenshots/manus.png",
      mediaClass: "media-gradient-10",
      mediaText: "General AI Agent",
      logo: "MN"
    },
    {
      id: "agent-autogpt",
      title: "AutoGPT",
      description: "开源自主 AI Agent 框架，支持目标分解、自主执行和记忆管理。",
      category: "开发框架",
      tags: ["开源", "自主", "框架"],
      url: "https://agpt.co/",
      screenshot: "screenshots/autogpt.png",
      mediaClass: "media-gradient-3",
      mediaText: "Autonomous Agent",
      logo: "AG"
    },
    {
      id: "agent-claude-code",
      title: "Claude Code",
      description: "Anthropic 推出的 AI 编程 Agent，支持终端内自主编码、调试和项目管理。",
      category: "编程Agent",
      tags: ["编程", "CLI", "调试"],
      url: "https://docs.anthropic.com/en/docs/claude-code",
      screenshot: "screenshots/claude-code.png",
      mediaClass: "media-gradient-6",
      mediaText: "Coding Agent",
      logo: "CC"
    },
    {
      id: "agent-devin",
      title: "Devin",
      description: "全球首个 AI 软件工程师，能独立完成从需求分析到代码部署的全流程开发。",
      category: "编程Agent",
      tags: ["全栈", "自主开发", "部署"],
      url: "https://devin.ai/",
      screenshot: "screenshots/devin.png",
      mediaClass: "media-gradient-2",
      mediaText: "AI Software Engineer",
      logo: "DV"
    }
  ],
  prompts: [
    {
      id: "prompt-writing",
      title: "万能写作助手",
      description: "根据主题、风格和目标受众，生成高质量文章大纲和初稿。",
      category: "写作",
      template: "请帮我写一篇关于[主题]的文章，目标读者是[受众]，风格要求[风格]，字数约[字数]字。"
    },
    {
      id: "prompt-code-review",
      title: "代码审查专家",
      description: "对代码进行全面审查，检查安全性、性能和可维护性。",
      category: "编程",
      template: "请审查以下代码，从安全性、性能、可读性和最佳实践四个维度给出改进建议：\n[代码]"
    },
    {
      id: "prompt-translate",
      title: "专业翻译官",
      description: "支持多语种互译，保持原文语气和专业术语准确性。",
      category: "翻译",
      template: "请将以下内容翻译为[目标语言]，保持原文的语气和风格，专业术语需准确：\n[原文]"
    },
    {
      id: "prompt-summary",
      title: "内容精炼器",
      description: "将长文本压缩为结构化摘要，保留核心观点和关键数据。",
      category: "效率",
      template: "请将以下内容精炼为一份结构化摘要，包含：核心观点、关键数据、行动建议。\n[长文本]"
    },
    {
      id: "prompt-xiaohongshu",
      title: "小红书爆款笔记",
      description: "生成符合小红书平台调性的种草笔记，含标题、正文和标签。",
      category: "营销",
      template: "请帮我写一篇小红书笔记，产品是[产品名]，卖点是[卖点]，目标人群是[人群]。要求：吸睛标题+emoji、口语化正文、5-8个相关标签。"
    },
    {
      id: "prompt-data-analysis",
      title: "数据分析师",
      description: "对数据进行多维度分析，输出可视化建议和业务洞察。",
      category: "分析",
      template: "请分析以下数据，给出：1)关键趋势 2)异常点 3)业务洞察 4)可视化建议。\n[数据]"
    }
  ],
  knowledgePicks: [
    {
      id: "pick-0320",
      title: "知识库精选 · 3月20日",
      summary: "AI 发展太快跟不上？一张四象限图帮你做减法 / 解析大语言模型中的KV缓存 / 50个Claude Code日常使用技巧与最佳实践 / OpenClaw 记忆系统演进系列（三）",
      url: "https://www.waytoagi.com/zh/blog/news-20260320",
      gradient: "media-gradient-1"
    },
    {
      id: "pick-0319",
      title: "知识库精选 · 3月19日",
      summary: "OpenClaw Skill技能系统3分钟秒懂教程 / 飞书2026春季发布会 / 你不知道的Agent：原理、架构与工程实践 / 什么是Vibe Design？",
      url: "https://www.waytoagi.com/zh/blog/news-20260319",
      gradient: "media-gradient-4"
    },
    {
      id: "pick-0318",
      title: "知识库精选 · 3月18日",
      summary: "MiniMax M2.7: 开启模型的自我进化 / OpenAI对话OpenClaw / 每个ADK开发者都应该了解的5种Agent Skill设计模式 / 构建Claude Code的经验",
      url: "https://www.waytoagi.com/zh/blog/news-20260318",
      gradient: "media-gradient-5"
    },
    {
      id: "pick-0317",
      title: "知识库精选 · 3月17日",
      summary: "OpenClaw多agent模式下Skills的分层调用机制 / Harness Engineering深度解读 / 黄仁勋2小时都发布了什么：英伟达GTC 2026全部重磅",
      url: "https://www.waytoagi.com/zh/blog/news-20260317",
      gradient: "media-gradient-7"
    },
    {
      id: "pick-0316",
      title: "知识库精选 · 3月16日",
      summary: "不要建一千个Agent：Ramp如何用一个Agent搞定金融自动化 / DeepSeek和Kimi捅破了Transformer的潜规则 / 本周AI Top论文速览",
      url: "https://www.waytoagi.com/zh/blog/news-20260316",
      gradient: "media-gradient-10"
    },
    {
      id: "pick-0315",
      title: "知识库精选 · 3月15日",
      summary: "保姆级OpenClaw+Claude Code术语全攻略 / 从底层机制讲透OpenClaw如何运行多Agents / AI记忆系统的核心公式 / 大白话读懂27个大语言模型核心概念",
      url: "https://www.waytoagi.com/zh/blog/news-20260315",
      gradient: "media-gradient-12"
    }
  ]
};
